name: Build & Test Algoloop

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: algoloop:foundation
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: dotnet build /p:Configuration=Release /v:quiet /p:WarningLevel=1 Algoloop.sln

      - name: Run Tests
        run: dotnet test ./Algoloop.Tests/bin/Release/Algoloop.Tests.dll --filter TestCategory=!LocalTest -- TestRunParameters.Parameter\(name=\"log-handler\", value=\"ConsoleErrorLogHandler\"\)

      - name: Generate & Publish python stubs
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          chmod +x ci_build_stubs.sh
          ./ci_build_stubs.sh -t -g -p
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
          ADDITIONAL_STUBS_REPOS: ${{ secrets.ADDITIONAL_STUBS_REPOS }}
          QC_GIT_TOKEN: ${{ secrets.QC_GIT_TOKEN }}
